

namespace Horizon.Application.DTOs
{
    public record CourseListDto(
         Guid Id,
         string Title,
         string? Subtitle,
         string? ShortDescription,
         string? ThumbnailUrl,
         string InstructorName,
         Guid InstructorId,
         string? InstructorAvatar,
         string Level,
         string Status,
         decimal Price,
         decimal? DiscountPrice,
         decimal CurrentPrice,
         bool HasDiscount,
         double AverageRating,
         int TotalReviews,
         int TotalStudents,
         int TotalLessons,
         int DurationMinutes,
         bool IsFeatured,
         List<string> Categories,
         List<string> Tags,
         DateTime CreatedAt);

    public record CourseDetailDto(
        Guid Id,
        string Title,
        string? Subtitle,
        string Description,
        string? ShortDescription,
        string? ThumbnailUrl,
        string? PromoVideoUrl,
        string? Language,
        string Level,
        string Status,
        decimal Price,
        decimal? DiscountPrice,
        decimal CurrentPrice,
        bool HasDiscount,
        string Currency,
        int DurationMinutes,
        bool IsFeatured,
        bool IsLifetimeAccess,
        int? AccessDays,
        string? Prerequisites,
        string? LearningObjectives,
        string? TargetAudience,
        string? WelcomeMessage,
        double AverageRating,
        int TotalReviews,
        int TotalStudents,
        int TotalLessons,
        InstructorDto Instructor,
        List<CategoryDto> Categories,
        List<TagDto> Tags,
        List<SectionDto> Sections,
        List<ReviewDto> RecentReviews,
        bool IsEnrolled,
        bool IsInWishlist,
        bool IsInCart,
        double? UserProgress,
        DateTime CreatedAt);

    public record CreateCourseDto(
        string Title,
        string? Subtitle,
        string Description,
        string? ShortDescription,
        string Level,
        decimal Price,
        decimal? DiscountPrice,
        DateTime? DiscountExpiry,
        string? Language,
        string? Prerequisites,
        string? LearningObjectives,
        string? TargetAudience,
        List<Guid> CategoryIds,
        List<Guid> TagIds);

    public record UpdateCourseDto(
        string? Title,
        string? Subtitle,
        string? Description,
        string? ShortDescription,
        string? Level,
        decimal? Price,
        decimal? DiscountPrice,
        DateTime? DiscountExpiry,
        string? Language,
        string? Prerequisites,
        string? LearningObjectives,
        string? TargetAudience,
        string? WelcomeMessage,
        string? CongratulationMessage,
        List<Guid>? CategoryIds,
        List<Guid>? TagIds);

    public record CourseSearchDto(
        string? Query,
        Guid? CategoryId,
        Guid? TagId,
        string? Level,
        decimal? MinPrice,
        decimal? MaxPrice,
        double? MinRating,
        string? Language,
        bool? IsFeatured,
        bool? IsFree,
        int Page = 1,
        int PageSize = 20,
        string SortBy = "CreatedAt",
        bool Descending = true);
}
